/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Ghost.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Ghost.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.arch_gate_left.geometry} material={materials['HalloweenBits.001']} position={[0.015, 0, 0]} rotation={[0, 0.611, 0]} />
      <mesh geometry={nodes.arch_gate_right.geometry} material={materials['HalloweenBits.001']} position={[-0.015, 0, 0]} />
      <mesh geometry={nodes.post_lantern_lantern.geometry} material={materials['HalloweenBits.048']} position={[0, 0.03, 0.01]} />
      <mesh geometry={nodes.post_skull_skull.geometry} material={materials['HalloweenBits.049']} position={[0, 0.03, 0.01]} />
      <mesh geometry={nodes.tree_pine_orange_small.geometry} material={materials['HalloweenBits.004']} position={[-9.5, 0, -9.1]} scale={100} />
      <mesh geometry={nodes.tree_pine_yellow_small001.geometry} material={materials['HalloweenBits.005']} position={[12, 0, -2]} scale={100} />
      <mesh geometry={nodes.tree_pine_yellow_medium.geometry} material={materials['HalloweenBits.006']} position={[-8, 0, -13]} scale={100} />
      <mesh geometry={nodes.tree_pine_orange_large.geometry} material={materials['HalloweenBits.007']} position={[-11.8, 0, -12.2]} scale={100} />
      <mesh geometry={nodes.bone_A.geometry} material={materials['HalloweenBits.010']} position={[9.3, 0, 3.4]} rotation={[0, Math.PI / 4, 0]} scale={100} />
      <mesh geometry={nodes.bone_B.geometry} material={materials['HalloweenBits.012']} position={[11.3, 0, -0.7]} scale={100} />
      <mesh geometry={nodes.candle_thin.geometry} material={materials['HalloweenBits.014']} position={[-6.1, 0, -1.7]} scale={100} />
      <mesh geometry={nodes.candle_melted.geometry} material={materials['HalloweenBits.015']} position={[-7.2, 0, -1.2]} scale={100} />
      <mesh geometry={nodes.candle.geometry} material={materials['HalloweenBits.016']} position={[-6, 0, -2.3]} scale={100} />
      <mesh geometry={nodes.candle_triple.geometry} material={materials['HalloweenBits.017']} position={[-6.1, 0, -2]} scale={100} />
      <mesh geometry={nodes.path_A002.geometry} material={materials['HalloweenBits.018']} />
      <mesh geometry={nodes.coffin.geometry} material={materials['HalloweenBits.019']} position={[-11, 0, 8]} scale={100}>
        <mesh geometry={nodes.coffin_lid.geometry} material={materials['HalloweenBits.019']} position={[-0.005, 0, 0.001]} rotation={[0, 0.461, 0]} />
      </mesh>
      <mesh geometry={nodes.tree_dead_large.geometry} material={materials['HalloweenBits.024']} position={[-8, 0, 2]} rotation={[0, 0.175, 0]} scale={100} />
      <mesh geometry={nodes.tree_dead_large001.geometry} material={materials['HalloweenBits.024']} position={[-8, 0, -11]} rotation={[0, 0.96, 0]} scale={100} />
      <mesh geometry={nodes.tree_dead_large002.geometry} material={materials['HalloweenBits.024']} position={[4, 0, -8]} rotation={[0, 1.309, 0]} scale={100} />
      <mesh geometry={nodes.tree_dead_medium.geometry} material={materials['HalloweenBits.025']} position={[7, 0, -5]} scale={100} />
      <group position={[-8, 0, 4]} scale={100}>
        <mesh geometry={nodes.floor_dirt_1.geometry} material={materials['HalloweenBits.026']} />
        <mesh geometry={nodes.floor_dirt_2.geometry} material={materials['HalloweenBits.034']} />
        <mesh geometry={nodes.floor_dirt_3.geometry} material={materials['HalloweenBits.031']} />
      </group>
      <mesh geometry={nodes.fence_gate.geometry} material={materials['HalloweenBits.029']} position={[-4, 0, -16]} scale={100}>
        <mesh geometry={nodes.fence_gate_left.geometry} material={materials['HalloweenBits.029']} position={[0.015, 0, 0]} />
        <mesh geometry={nodes.fence_gate_right.geometry} material={materials['HalloweenBits.029']} position={[-0.015, 0, 0]} />
      </mesh>
      <mesh geometry={nodes.gravemarker_B.geometry} material={materials['HalloweenBits.035']} position={[7.3, 0, 5.6]} rotation={[0, 0.175, 0]} scale={100} />
      <mesh geometry={nodes.grave_B.geometry} material={materials['HalloweenBits.037']} position={[-5.4, 0, -12.9]} rotation={[0, -1.571, 0]} scale={100} />
      <mesh geometry={nodes.lantern_standing.geometry} material={materials['HalloweenBits.041']} position={[3.028, 2.115, 4.118]} scale={100} />
      <mesh geometry={nodes.path_B002.geometry} material={materials['HalloweenBits.042']} />
      <group position={[1.1, 0, 1.9]} rotation={[0, 1.571, 0]} scale={100}>
        <mesh geometry={nodes.path_B003_1.geometry} material={materials['HalloweenBits.042']} />
        <mesh geometry={nodes.path_B003_2.geometry} material={materials['HalloweenBits.018']} />
      </group>
      <mesh geometry={nodes.path_B004.geometry} material={materials['HalloweenBits.042']} />
      <mesh geometry={nodes.path_B005.geometry} material={materials['HalloweenBits.042']} position={[-5.009, -0.079, 10.994]} scale={100} />
      <mesh geometry={nodes.path_B006.geometry} material={materials['HalloweenBits.042']} position={[12.973, 0, 6.936]} scale={100} />
      <mesh geometry={nodes.path_B007.geometry} material={materials['HalloweenBits.042']} position={[-13.049, 0, 10.974]} scale={100} />
      <mesh geometry={nodes.path_B008.geometry} material={materials['HalloweenBits.042']} position={[4.991, 0.002, 10.995]} scale={100} />
      <mesh geometry={nodes.path_C.geometry} material={materials['HalloweenBits.043']} position={[6.887, 0.001, 10.993]} scale={100} />
      <mesh geometry={nodes.path_C001.geometry} material={materials['HalloweenBits.043']} position={[-11.007, 0, 0.946]} rotation={[Math.PI, 0, Math.PI]} scale={100} />
      <mesh geometry={nodes.path_C002.geometry} material={materials['HalloweenBits.043']} position={[-11, 0, -1]} rotation={[0, -1.571, 0]} scale={100} />
      <mesh geometry={nodes.post.geometry} material={materials['HalloweenBits.047']} position={[3, 0, 3]} scale={100} />
      <mesh geometry={nodes.pumpkin_orange.geometry} material={materials['HalloweenBits.050']} position={[4.8, 0, 5.4]} rotation={[0, -0.611, 0]} scale={100} />
      <mesh geometry={nodes.ribcage.geometry} material={materials['HalloweenBits.052']} position={[-3.9, 0.246, -12.9]} scale={100} />
      <mesh geometry={nodes.path_D.geometry} material={materials['HalloweenBits.053']} position={[-1.1, 0, 9.8]} scale={100} />
      <mesh geometry={nodes.path_D001.geometry} material={materials['HalloweenBits.053']} position={[-8.7, 0, -4.2]} scale={100} />
      <mesh geometry={nodes.path_D002.geometry} material={materials['HalloweenBits.053']} position={[4.963, 0, -4.026]} rotation={[-Math.PI, 1.309, -Math.PI]} scale={100} />
      <mesh geometry={nodes.shrine.geometry} material={materials['HalloweenBits.054']} position={[6, 0, -10]} scale={100} />
      <mesh geometry={nodes.tree_dead_small.geometry} material={materials['HalloweenBits.058']} position={[9, 0, -15]} rotation={[Math.PI, -0.698, Math.PI]} scale={100} />
      <mesh geometry={nodes.pumpkin_orange_small.geometry} material={materials['HalloweenBits.060']} position={[-9.5, 0, -6.7]} scale={100} />
      <mesh geometry={nodes.pumpkin_orange_small001.geometry} material={materials['HalloweenBits.060']} position={[-4.8, 0, 5.6]} rotation={[0, 0.436, 0]} scale={100} />
      <mesh geometry={nodes.pumpkin_yellow_small.geometry} material={materials['HalloweenBits.062']} position={[5.4, 0, 5.8]} scale={100} />
    </group>
  )
}

useGLTF.preload('/Ghost.glb')
